{
 "title": "node cpu",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(node_boot_time{job=\"node-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU-9.21.141.182",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.21.141.182:9100\"}[5m])) * 100)",
     "legendFormat": "9.21.141.182:9100"
    }
   ]
  },
  {
   "title": "CPU-9.21.142.17",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.21.142.17:9100\"}[5m])) * 100)",
     "legendFormat": "9.21.142.17:9100"
    }
   ]
  },
  {
   "title": "CPU-9.21.146.126",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.21.146.126:9100\"}[5m])) * 100)",
     "legendFormat": "9.21.146.126:9100"
    }
   ]
  },
  {
   "title": "CPU-9.21.152.226",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.21.152.226:9100\"}[5m])) * 100)",
     "legendFormat": "9.21.152.226:9100"
    }
   ]
  },
  {
   "title": "CPU-9.22.0.50",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.22.0.50:9100\"}[5m])) * 100)",
     "legendFormat": "9.22.0.50:9100"
    }
   ]
  },
  {
   "title": "CPU-9.22.25.15",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.22.25.15:9100\"}[5m])) * 100)",
     "legendFormat": "9.22.25.15:9100"
    }
   ]
  },
  {
   "title": "CPU-9.22.25.222",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.22.25.222:9100\"}[5m])) * 100)",
     "legendFormat": "9.22.25.222:9100"
    }
   ]
  },
  {
   "title": "CPU-9.37.172.11",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.37.172.11:9100\"}[5m])) * 100)",
     "legendFormat": "9.37.172.11:9100"
    }
   ]
  },
  {
   "title": "CPU-9.37.172.19",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.37.172.19:9100\"}[5m])) * 100)",
     "legendFormat": "9.37.172.19:9100"
    }
   ]
  },
  {
   "title": "CPU-9.37.172.29",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.37.172.29:9100\"}[5m])) * 100)",
     "legendFormat": "9.37.172.29:9100"
    }
   ]
  },
  {
   "title": "CPU-9.37.172.41",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.37.172.41:9100\"}[5m])) * 100)",
     "legendFormat": "9.37.172.41:9100"
    }
   ]
  },
  {
   "title": "CPU-9.37.172.58",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.37.172.58:9100\"}[5m])) * 100)",
     "legendFormat": "9.37.172.58:9100"
    }
   ]
  },
  {
   "title": "CPU-9.37.172.61",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.37.172.61:9100\"}[5m])) * 100)",
     "legendFormat": "9.37.172.61:9100"
    }
   ]
  },
  {
   "title": "CPU-9.44.11.30",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.44.11.30:9100\"}[5m])) * 100)",
     "legendFormat": "9.44.11.30:9100"
    }
   ]
  },
  {
   "title": "CPU-9.44.11.34",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.44.11.34:9100\"}[5m])) * 100)",
     "legendFormat": "9.44.11.34:9100"
    }
   ]
  },
  {
   "title": "CPU-9.56.33.219",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.56.33.219:9100\"}[5m])) * 100)",
     "legendFormat": "9.56.33.219:9100"
    }
   ]
  },
  {
   "title": "CPU-9.56.45.36",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.56.45.36:9100\"}[5m])) * 100)",
     "legendFormat": "9.56.45.36:9100"
    }
   ]
  },
  {
   "title": "CPU-9.80.48.147",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.80.48.147:9100\"}[5m])) * 100)",
     "legendFormat": "9.80.48.147:9100"
    }
   ]
  },
  {
   "title": "CPU-9.80.48.196",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.80.48.196:9100\"}[5m])) * 100)",
     "legendFormat": "9.80.48.196:9100"
    }
   ]
  },
  {
   "title": "CPU-9.80.48.210",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.80.48.210:9100\"}[5m])) * 100)",
     "legendFormat": "9.80.48.210:9100"
    }
   ]
  },
  {
   "title": "CPU-9.80.60.29",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.80.60.29:9100\"}[5m])) * 100)",
     "legendFormat": "9.80.60.29:9100"
    }
   ]
  },
  {
   "title": "CPU-9.80.64.89",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.80.64.89:9100\"}[5m])) * 100)",
     "legendFormat": "9.80.64.89:9100"
    }
   ]
  },
  {
   "title": "CPU-9.80.101.12",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"9.80.101.12:9100\"}[5m])) * 100)",
     "legendFormat": "9.80.101.12:9100"
    }
   ]
  },
  {
   "title": "CPU-10.55.212.182",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"10.55.212.182:9100\"}[5m])) * 100)",
     "legendFormat": "10.55.212.182:9100"
    }
   ]
  },
  {
   "title": "CPU-10.55.215.247",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"10.55.215.247:9100\"}[5m])) * 100)",
     "legendFormat": "10.55.215.247:9100"
    }
   ]
  },
  {
   "title": "CPU-10.56.17.157",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"10.56.17.157:9100\"}[5m])) * 100)",
     "legendFormat": "10.56.17.157:9100"
    }
   ]
  },
  {
   "title": "CPU-10.56.214.190",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"10.56.214.190:9100\"}[5m])) * 100)",
     "legendFormat": "10.56.214.190:9100"
    }
   ]
  },
  {
   "title": "CPU-10.56.214.210",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"10.56.214.210:9100\"}[5m])) * 100)",
     "legendFormat": "10.56.214.210:9100"
    }
   ]
  },
  {
   "title": "CPU-10.56.216.249",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"10.56.216.249:9100\"}[5m])) * 100)",
     "legendFormat": "10.56.216.249:9100"
    }
   ]
  },
  {
   "title": "CPU-10.57.17.185",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"10.57.17.185:9100\"}[5m])) * 100)",
     "legendFormat": "10.57.17.185:9100"
    }
   ]
  },
  {
   "title": "CPU-10.57.21.175",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"10.57.21.175:9100\"}[5m])) * 100)",
     "legendFormat": "10.57.21.175:9100"
    }
   ]
  },
  {
   "title": "CPU-10.57.21.198",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"10.57.21.198:9100\"}[5m])) * 100)",
     "legendFormat": "10.57.21.198:9100"
    }
   ]
  },
  {
   "title": "CPU-10.62.84.143",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"10.62.84.143:9100\"}[5m])) * 100)",
     "legendFormat": "10.62.84.143:9100"
    }
   ]
  },
  {
   "title": "CPU-100.107.140.67",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"100.107.140.67:9100\"}[5m])) * 100)",
     "legendFormat": "100.107.140.67:9100"
    }
   ]
  },
  {
   "title": "CPU-100.107.140.112",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"100.107.140.112:9100\"}[5m])) * 100)",
     "legendFormat": "100.107.140.112:9100"
    }
   ]
  },
  {
   "title": "CPU-100.107.140.114",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"100.107.140.114:9100\"}[5m])) * 100)",
     "legendFormat": "100.107.140.114:9100"
    }
   ]
  },
  {
   "title": "CPU-100.107.141.81",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"100.107.141.81:9100\"}[5m])) * 100)",
     "legendFormat": "100.107.141.81:9100"
    }
   ]
  },
  {
   "title": "CPU-100.107.141.103",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"100.107.141.103:9100\"}[5m])) * 100)",
     "legendFormat": "100.107.141.103:9100"
    }
   ]
  },
  {
   "title": "CPU-100.115.160.86",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"100.115.160.86:9100\"}[5m])) * 100)",
     "legendFormat": "100.115.160.86:9100"
    }
   ]
  }
 ]
}