{
 "title": "clickhouse-各db负载差异",
 "description": "Clickhouse metrics, Monitoring Agent metrics",
 "tags": [
  "clickhouse",
  "Altinity",
  "operator"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "process read bytes (G)",
   "type": "grafana-piechart-panel",
   "description": "Show network errors and distributed server-server connections failures",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(system_processes_read_bytes)by(database)/1000000000",
     "legendFormat": " {{database}}"
    }
   ]
  },
  {
   "title": "process written_bytes (G)",
   "type": "grafana-piechart-panel",
   "description": "Show network errors and distributed server-server connections failures",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(system_processes_written_bytes)by(database)/1000000000",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "merge bytes_written_uncompressed(G) ",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(system_merges_bytes_written_uncompressed/1000000000)by(database)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "merge bytes_read_uncompressed(G) ",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(system_merges_bytes_read_uncompressed/1000000000)by(database)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "parts bytes_on_disk(G) ",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(system_parts_bytes_on_disk/1000000000)by(database)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "parts data_uncompressed_bytes(G) ",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 16 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(system_parts_data_uncompressed_bytes/1000000000)by(database)",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}