{
 "title": "clickhouse-dashboard",
 "description": "Clickhouse metrics, Monitoring Agent metrics",
 "tags": [
  "clickhouse",
  "Altinity",
  "operator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ip",
    "label": "ip",
    "query": "label_values(system_events_value, ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "database num",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_databases_num{ip=~\"$ip\"}",
     "legendFormat": "database num {{ip}}"
    }
   ]
  },
  {
   "title": "tables num",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(system_tables_num{ip=~\"$ip\"})by(ip)",
     "legendFormat": "table number {{ip}}"
    }
   ]
  },
  {
   "title": "columns num",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(system_columns_num{ip=~\"$ip\"})by(ip)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "total query num",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_events_value{event='Query',ip=~\"$ip\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "total select num",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_events_value{event='SelectQuery',ip=~\"$ip\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "total fileopen num",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_events_value{event='FileOpen',ip=~\"$ip\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "network_receive（million）",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{job=\"node-exporter\", instance=~\"$ip:9100\", device!~\"lo\"}[5m])/1000000)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\", instance=~\"$ip:9100\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=~\"$ip:9100\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=~\"$ip:9100\"}\n- node_memory_Cached{job=\"node-exporter\", instance=~\"$ip:9100\"}\n) * 100\n  /\nnode_memory_MemTotal{job=\"node-exporter\", instance=~\"$ip:9100\"}\n"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"$ip:9100\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  sum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=~\"$ip:9100\"})\n- sum(node_filesystem_avail{job=\"node-exporter\", device!=\"rootfs\", instance=~\"$ip:9100\"})\n) * 100\n  /\nsum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=~\"$ip:9100\"})\n"
    }
   ]
  },
  {
   "title": "io read（million）",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_bytes_read{job=\"node-exporter\", instance=~\"$ip:9100\"}[2m])/1000000)by(instance)",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "io write（million）",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_bytes_written{job=\"node-exporter\", instance=~\"$ip:9100\"}[2m])/1000000)by(instance)",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "network_transmit（million）",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes{job=\"node-exporter\", instance=~\"$ip:9100\", device!~\"lo\"}[5m])/1000000)"
    }
   ]
  },
  {
   "title": "rannk size/written/read",
   "type": "graph",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "queries / sec" }
   ],
   "targets": [
    {
     "expr": "topk(1,sum(system_merges_bytes_written_uncompressed/1000000000)by(ip))",
     "legendFormat": "{{ip}} bytes_written_uncompressed(G) "
    }
   ]
  },
  {
   "title": "event query/select/fileopen increase num in 10minute",
   "type": "graph",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "queries / sec" }
   ],
   "targets": [
    {
     "expr": "increase(system_events_value{event='Query',ip=~\"$ip\"}[10m])",
     "legendFormat": "query number {{ip}}"
    },
    {
     "expr": "increase(system_events_value{event='SelectQuery',ip=~\"$ip\"}[10m])",
     "legendFormat": "SelectQuery number {{ip}}"
    }
   ]
  },
  {
   "title": "merge elapsed(s)",
   "type": "graph",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "queries / sec" }
   ],
   "targets": [
    {
     "expr": "avg(system_merges_elapsed{ip=~\"$ip\"})by(ip)",
     "legendFormat": "elapsed time {{ip}}"
    }
   ]
  },
  {
   "title": "merge num_parts rows/size/written/read",
   "type": "graph",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "queries / sec" }
   ],
   "targets": [
    {
     "expr": "sum(system_merges_num_parts{ip=~\"$ip\"})by(ip)",
     "legendFormat": "num_parts "
    },
    {
     "expr": "sum(system_merges_total_size_bytes_compressed{ip=~\"$ip\"}/1000000000)by(ip)",
     "legendFormat": "total_size_bytes_compressed(G) "
    },
    {
     "expr": "sum(system_merges_total_size_marks{ip=~\"$ip\"}/1000000)by(ip)",
     "legendFormat": "total_size_marks(million) "
    },
    {
     "expr": "sum(system_merges_bytes_read_uncompressed{ip=~\"$ip\"}/1000000000)by(ip)",
     "legendFormat": "bytes_read_uncompressed(G) "
    },
    {
     "expr": "sum(system_merges_rows_read{ip=~\"$ip\"}/1000000)by(ip)",
     "legendFormat": "rows_read(million) "
    },
    {
     "expr": "sum(system_merges_bytes_written_uncompressed{ip=~\"$ip\"}/1000000000)by(ip)",
     "legendFormat": "bytes_written_uncompressed(G) "
    },
    {
     "expr": "sum(system_merges_rows_written{ip=~\"$ip\"}/1000000)by(ip)",
     "legendFormat": "rows_written(million)"
    }
   ]
  },
  {
   "title": "process start time",
   "type": "graph",
   "description": "Show network errors and distributed server-server connections failures",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(system_processes_elapsed{ip=~\"$ip\"})by(ip)",
     "legendFormat": "elapsed {{ip}}"
    }
   ]
  },
  {
   "title": "process read/write row num",
   "type": "graph",
   "description": "Show network errors and distributed server-server connections failures",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(system_processes_read_rows{ip=~\"$ip\"})by(ip)",
     "legendFormat": "read_rows {{ip}}"
    },
    {
     "expr": "sum(system_processes_written_rows{ip=~\"$ip\"})by(ip)",
     "legendFormat": "written_rows {{ip}}"
    }
   ]
  },
  {
   "title": "process read/write bytes",
   "type": "graph",
   "description": "Show network errors and distributed server-server connections failures",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(system_processes_read_bytes{ip=~\"$ip\"})by(ip)",
     "legendFormat": "read_bytes {{ip}}"
    },
    {
     "expr": "sum(system_processes_written_bytes{ip=~\"$ip\"})by(ip)",
     "legendFormat": "written_bytes {{ip}}"
    }
   ]
  },
  {
   "title": "process peak/memory_usage",
   "type": "graph",
   "description": "Show network errors and distributed server-server connections failures",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(system_processes_memory_usage{ip=~\"$ip\"})by(ip)",
     "legendFormat": "memory_usage {{ip}}"
    },
    {
     "expr": "avg(system_processes_peak_memory_usage{ip=~\"$ip\"})by(ip)",
     "legendFormat": "peak_memory_usage {{ip}}"
    }
   ]
  },
  {
   "title": "metrics query/merge/Mutation number",
   "type": "graph",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "queries / sec" }
   ],
   "targets": [
    {
     "expr": "system_metrics_value{metric=\"Query\",ip=~\"$ip\"}",
     "legendFormat": "query {{ip}}"
    },
    {
     "expr": "system_metrics_value{metric=\"Merge\",ip=~\"$ip\"}",
     "legendFormat": "merge {{ip}}"
    },
    {
     "expr": "system_metrics_value{metric=\"PartMutation\",ip=~\"$ip\"}",
     "legendFormat": "PartMutation {{ip}}"
    }
   ]
  },
  {
   "title": "replicas-metric fetched/send/check number",
   "type": "graph",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "queries / sec" }
   ],
   "targets": [
    {
     "expr": "system_metrics_value{metric=\"ReplicatedFetch\",ip=~\"$ip\"}",
     "legendFormat": "fetch {{ip}}"
    },
    {
     "expr": "system_metrics_value{metric=\"ReplicatedSend\",ip=~\"$ip\"}",
     "legendFormat": "send {{ip}}"
    },
    {
     "expr": "system_metrics_value{metric=\"ReplicatedChecks\",ip=~\"$ip\"}",
     "legendFormat": "check {{ip}}"
    }
   ]
  },
  {
   "title": "task-metric Process/Schedule number",
   "type": "graph",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "queries / sec" }
   ],
   "targets": [
    {
     "expr": "system_metrics_value{metric=\"BackgroundSchedulePoolTask\",ip=~\"$ip\"}",
     "legendFormat": "BackgroundSchedulePoolTask {{ip}}"
    },
    {
     "expr": "system_metrics_value{metric=\"BackgroundPoolTask\",ip=~\"$ip\"}",
     "legendFormat": "BackgroundPoolTask {{ip}}"
    }
   ]
  },
  {
   "title": "asynchronous_metrics  background_thread",
   "type": "graph",
   "description": "DelayedInserts\n\nNumber of INSERT queries that are throttled due to high number of active data parts for partition in a MergeTree table.\n\nMaxPartCountForPartition\nMaximum active parts on one Partition per server",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_asynchronous_metrics_value{metric=\"jemalloc.background_thread.num_runs\",ip=~\"$ip\"}",
     "legendFormat": "num_runs {{ip}}"
    },
    {
     "expr": "system_asynchronous_metrics_value{metric=\"jemalloc.background_thread.num_threads\",ip=~\"$ip\"}",
     "legendFormat": "num_threads {{ip}}"
    }
   ]
  },
  {
   "title": "asynchronous_metrics  jemalloc(G)",
   "type": "graph",
   "description": "Show readonly and partial shutdown replicas, zookeeer exceptions, zookeeer sessions, zookeeper init requests",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_asynchronous_metrics_value{metric=\"jemalloc.retained\",ip=~\"$ip\"}/1024/1024/1024",
     "legendFormat": "retained {{ip}}"
    },
    {
     "expr": "system_asynchronous_metrics_value{metric=\"jemalloc.mapped\",ip=~\"$ip\"}/1024/1024/1024",
     "legendFormat": "mapped  {{ip}}"
    },
    {
     "expr": "system_asynchronous_metrics_value{metric=\"jemalloc.resident\",ip=~\"$ip\"}/1024/1024/1024",
     "legendFormat": "resident {{ip}}"
    },
    {
     "expr": "system_asynchronous_metrics_value{metric=\"jemalloc.metadata_thp\",ip=~\"$ip\"}/1024/1024/1024",
     "legendFormat": "metadata_thp {{ip}}"
    },
    {
     "expr": "system_asynchronous_metrics_value{metric=\"jemalloc.metadata\",ip=~\"$ip\"}/1024/1024/1024",
     "legendFormat": "metadata {{ip}}"
    }
   ]
  }
 ]
}