{
 "title": "ClickHouse Queries",
 "description": "Helps to visualize most frequent, slowest, failed queries.\r\nShows queries rate per second, table with last queries",
 "tags": [
  "clickhouse",
  "performance"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "5m" },
   { "name": "type", "label": "type", "query": "1,2,3,4" },
   { "name": "top", "label": "top elements", "query": "5,10,15,20,25,30" },
   {
    "name": "user",
    "label": "initial user",
    "query": "select distinct initial_user from system.query_log where event_date >= today()-3 and event_time > toDateTime(today()-3)"
   },
   { "name": "query_type", "label": "query type", "query": "all,select,insert" }
  ]
 },
 "panels": [
  { "title": "Top charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "分钟级插入数据字节TOPN",
   "type": "graph",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rateColumns</font>(<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">45</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"navajowhite\">cityHash64</font>(query) <font color=\"darkorange\">global</font> <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> <font color=\"navajowhite\">cityHash64</font>(<font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">45</font>)) <font color=\"darkorange\">AS</font> h<br />    <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />    <font color=\"darkorange\">WHERE</font><br />        <font color=\"darkcyan\">$timeFilter</font><br />        <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />        <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />        <font color=\"yellow\">AND</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br />    <font color=\"darkorange\">GROUP BY</font> h<br />    <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">count</font>() <font color=\"darkorange\">desc</font><br />    <font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>)<br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">AND</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM \r\n\t(SELECT t, groupArray((query, c)) AS groupArr FROM \r\n\t\t( SELECT (intDiv(toUInt32(event_time), 60) * 60)*1000 AS t, substring(query, 1, 60) AS query, sum(written_bytes) c FROM\r\n\t\t\t\tgrafana_monitor.query_log_all \r\n\t\t  WHERE $timeFilter AND     cityHash64(query) global in (\r\n\t\t\t\tSELECT cityHash64(substring(query,  1,  60)) AS h     FROM \r\n\t\t\t\t\t\tgrafana_monitor.query_log_all   \r\n\t\t\t\tWHERE         $timeFilter         \r\n\t\t\t\t\tAND type in ($type)         \r\n\t\t\t\t\tAND initial_user in ($user)         \r\n\t\t\t\t\tAND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))     \r\n\t\t\t\tGROUP BY h     ORDER BY sum(written_bytes) desc     LIMIT $top)\r\n\t\t\tAND type in ($type)     \r\n\t\t\tAND initial_user in ($user)     \r\n\t\t\tAND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1)) \r\n\t\tGROUP BY t, query ORDER BY t, query\r\n\t\t) \r\n\tGROUP BY t ORDER BY t\r\n\t)",
     "rawQuery": "SELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM  \t(SELECT t, groupArray((query, c)) AS groupArr FROM  \t\t( SELECT (intDiv(toUInt32(event_time), 60) * 60)*1000 AS t, substring(query, 1, 60) AS query, sum(written_bytes) c FROM \t\t\t\tgrafana_monitor.query_log_all  \t\t  WHERE event_date >= toDate(1584600670) AND event_time >= toDateTime(1584600670) AND     cityHash64(query) global in ( \t\t\t\tSELECT cityHash64(substring(query,  1,  60)) AS h     FROM  \t\t\t\t\t\tgrafana_monitor.query_log_all    \t\t\t\tWHERE         event_date >= toDate(1584600670) AND event_time >= toDateTime(1584600670)          \t\t\t\t\tAND type in (1,2,3,4)          \t\t\t\t\tAND initial_user in ('default','qqmusic_search_user','','qqmusic_live_user','qqmusic_log_only_user')          \t\t\t\t\tAND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))      \t\t\t\tGROUP BY h     ORDER BY sum(written_bytes) desc     LIMIT 5) \t\t\tAND type in (1,2,3,4)      \t\t\tAND initial_user in ('default','qqmusic_search_user','','qqmusic_live_user','qqmusic_log_only_user')      \t\t\tAND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))  \t\tGROUP BY t, query ORDER BY t, query \t\t)  \tGROUP BY t ORDER BY t \t)",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Types",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "content": "1 - successful start of query execution\n\n2 - successful end of query execution\n\n3 - exception before start of query execution\n\n4 - exception while query execution"
  },
  {
   "title": "分钟级插入数据字节TOPN",
   "type": "graph",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rateColumns</font>(<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">45</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"navajowhite\">cityHash64</font>(query) <font color=\"darkorange\">global</font> <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> <font color=\"navajowhite\">cityHash64</font>(<font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">45</font>)) <font color=\"darkorange\">AS</font> h<br />    <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />    <font color=\"darkorange\">WHERE</font><br />        <font color=\"darkcyan\">$timeFilter</font><br />        <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />        <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />        <font color=\"yellow\">AND</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br />    <font color=\"darkorange\">GROUP BY</font> h<br />    <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">count</font>() <font color=\"darkorange\">desc</font><br />    <font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>)<br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">AND</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM \r\n\t(SELECT t, groupArray((query, c)) AS groupArr FROM \r\n\t\t( SELECT (intDiv(toUInt32(event_time), 60) * 60)*1000 AS t, substring(query, 1, 60) AS query, sum(written_bytes) c FROM\r\n\t\t\t\tsystem.query_log \r\n\t\t  WHERE $timeFilter AND     cityHash64(query) global in (\r\n\t\t\t\tSELECT cityHash64(substring(query,  1,  60)) AS h     FROM \r\n\t\t\t\t\t\tsystem.query_log   \r\n\t\t\t\tWHERE         $timeFilter         \r\n\t\t\t\t\tAND type in ($type)         \r\n\t\t\t\t\tAND initial_user in ($user)         \r\n\t\t\t\t\tAND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))     \r\n\t\t\t\tGROUP BY h     ORDER BY sum(written_bytes) desc     LIMIT $top)\r\n\t\t\tAND type in ($type)     \r\n\t\t\tAND initial_user in ($user)     \r\n\t\t\tAND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1)) \r\n\t\tGROUP BY t, query ORDER BY t, query\r\n\t\t) \r\n\tGROUP BY t ORDER BY t\r\n\t)",
     "rawQuery": "SELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM  \t(SELECT t, groupArray((query, c)) AS groupArr FROM  \t\t( SELECT (intDiv(toUInt32(event_time), 60) * 60)*1000 AS t, substring(query, 1, 60) AS query, sum(written_bytes) c FROM \t\t\t\tsystem.query_log  \t\t  WHERE event_date >= toDate(1584600671) AND event_time >= toDateTime(1584600671) AND     cityHash64(query) global in ( \t\t\t\tSELECT cityHash64(substring(query,  1,  60)) AS h     FROM  \t\t\t\t\t\tsystem.query_log    \t\t\t\tWHERE         event_date >= toDate(1584600671) AND event_time >= toDateTime(1584600671)          \t\t\t\t\tAND type in (1,2,3,4)          \t\t\t\t\tAND initial_user in ('default','qqmusic_search_user','','qqmusic_live_user','qqmusic_log_only_user')          \t\t\t\t\tAND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))      \t\t\t\tGROUP BY h     ORDER BY sum(written_bytes) desc     LIMIT 5) \t\t\tAND type in (1,2,3,4)      \t\t\tAND initial_user in ('default','qqmusic_search_user','','qqmusic_live_user','qqmusic_log_only_user')      \t\t\tAND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))  \t\tGROUP BY t, query ORDER BY t, query \t\t)  \tGROUP BY t ORDER BY t \t)",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "5秒级内存占用排行榜",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rateColumns</font>(<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">45</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"navajowhite\">cityHash64</font>(query) <font color=\"darkorange\">global</font> <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> <font color=\"navajowhite\">cityHash64</font>(<font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">45</font>)) <font color=\"darkorange\">AS</font> h<br />    <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />    <font color=\"darkorange\">WHERE</font><br />        <font color=\"darkcyan\">$timeFilter</font><br />        <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />        <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />        <font color=\"yellow\">AND</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br />    <font color=\"darkorange\">GROUP BY</font> h<br />    <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">count</font>() <font color=\"darkorange\">desc</font><br />    <font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>)<br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">AND</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM \r\n\t(SELECT t, groupArray((query, c)) AS groupArr FROM \r\n\t\t( SELECT (intDiv(toUInt32(event_time), 5) * 5)*1000 AS t, query AS query, sum(memory_usage) c FROM\r\n\t\t\t\tgrafana_monitor.query_log_all \r\n\t\t  WHERE $timeFilter AND     cityHash64(query) global in (\r\n\t\t\t\tSELECT cityHash64(query) AS h     FROM \r\n\t\t\t\t\t\tgrafana_monitor.query_log_all   \r\n\t\t\t\tWHERE         $timeFilter         \r\n\t\t\t\t\tAND type in ($type)         \r\n\t\t\t\t\tAND initial_user in ($user)         \r\n\t\t\t\t\tAND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))     \r\n\t\t\t\tGROUP BY h     ORDER BY sum(memory_usage) desc     LIMIT $top)\r\n\t\t\tAND type in ($type)     \r\n\t\t\tAND initial_user in ($user)     \r\n\t\t\tAND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1)) \r\n\t\tGROUP BY t, query ORDER BY t, query\r\n\t\t) \r\n\tGROUP BY t ORDER BY t\r\n\t)",
     "rawQuery": "SELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM  \t(SELECT t, groupArray((query, c)) AS groupArr FROM  \t\t( SELECT (intDiv(toUInt32(event_time), 5) * 5)*1000 AS t, query AS query, sum(memory_usage) c FROM \t\t\t\tgrafana_monitor.query_log_all  \t\t  WHERE event_date >= toDate(1584600670) AND event_time >= toDateTime(1584600670) AND     cityHash64(query) global in ( \t\t\t\tSELECT cityHash64(query) AS h     FROM  \t\t\t\t\t\tgrafana_monitor.query_log_all    \t\t\t\tWHERE         event_date >= toDate(1584600670) AND event_time >= toDateTime(1584600670)          \t\t\t\t\tAND type in (1,2,3,4)          \t\t\t\t\tAND initial_user in ('default','qqmusic_search_user','','qqmusic_live_user','qqmusic_log_only_user')          \t\t\t\t\tAND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))      \t\t\t\tGROUP BY h     ORDER BY sum(memory_usage) desc     LIMIT 5) \t\t\tAND type in (1,2,3,4)      \t\t\tAND initial_user in ('default','qqmusic_search_user','','qqmusic_live_user','qqmusic_log_only_user')      \t\t\tAND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))  \t\tGROUP BY t, query ORDER BY t, query \t\t)  \tGROUP BY t ORDER BY t \t)",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "秒级query次数TOPN",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkcyan\">$rateColumns</font>(<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">45</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"navajowhite\">cityHash64</font>(query) <font color=\"darkorange\">global</font> <font color=\"darkorange\">in</font> (<br />    <font color=\"darkorange\">SELECT</font> <font color=\"navajowhite\">cityHash64</font>(<font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">45</font>)) <font color=\"darkorange\">AS</font> h<br />    <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br />    <font color=\"darkorange\">WHERE</font><br />        <font color=\"darkcyan\">$timeFilter</font><br />        <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />        <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />        <font color=\"yellow\">AND</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br />    <font color=\"darkorange\">GROUP BY</font> h<br />    <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">count</font>() <font color=\"darkorange\">desc</font><br />    <font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>)<br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">AND</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">AND</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
     "query": "SELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM \r\n\t(SELECT t, groupArray((query, c)) AS groupArr FROM \r\n\t\t( SELECT (intDiv(toUInt32(event_time), 1) * 1)*1000 AS t, query AS query, count(*) c FROM\r\n\t\t\t\tgrafana_monitor.query_log_all \r\n\t\t  WHERE $timeFilter AND     cityHash64(query) global in (\r\n\t\t\t\tSELECT cityHash64(query) AS h     FROM \r\n\t\t\t\t\t\tgrafana_monitor.query_log_all   \r\n\t\t\t\tWHERE         $timeFilter        \r\n\t\t\t\t\tAND type in ($type)         \r\n\t\t\t\t\tAND initial_user in ($user)         \r\n\t\t\t\t\tAND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))     \r\n\t\t\t\tGROUP BY h     ORDER BY count(*) desc     LIMIT $top)\r\n\t\t\tAND type in ($type)     \r\n\t\t\tAND initial_user in ($user)     \r\n\t\t\tAND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1)) \r\n\t\tGROUP BY t, query ORDER BY t, query\r\n\t\t) \r\n\tGROUP BY t ORDER BY t\r\n\t)",
     "rawQuery": "SELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr) FROM  \t(SELECT t, groupArray((query, c)) AS groupArr FROM  \t\t( SELECT (intDiv(toUInt32(event_time), 1) * 1)*1000 AS t, query AS query, count(*) c FROM \t\t\t\tgrafana_monitor.query_log_all  \t\t  WHERE event_date >= toDate(1584600670) AND event_time >= toDateTime(1584600670) AND     cityHash64(query) global in ( \t\t\t\tSELECT cityHash64(query) AS h     FROM  \t\t\t\t\t\tgrafana_monitor.query_log_all    \t\t\t\tWHERE         event_date >= toDate(1584600670) AND event_time >= toDateTime(1584600670)         \t\t\t\t\tAND type in (1,2,3,4)          \t\t\t\t\tAND initial_user in ('default','qqmusic_search_user','','qqmusic_live_user','qqmusic_log_only_user')          \t\t\t\t\tAND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))      \t\t\t\tGROUP BY h     ORDER BY count(*) desc     LIMIT 5) \t\t\tAND type in (1,2,3,4)      \t\t\tAND initial_user in ('default','qqmusic_search_user','','qqmusic_live_user','qqmusic_log_only_user')      \t\t\tAND('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1))  \t\tGROUP BY t, query ORDER BY t, query \t\t)  \tGROUP BY t ORDER BY t \t)",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "clickhouse全库的表大小",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "database": "system",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "event_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"navajowhite\">rand</font>() <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">substring</font>(query,  <font color=\"cornflowerblue\">1</font>,  <font color=\"cornflowerblue\">70</font>) <font color=\"darkorange\">AS</font> query,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) duration,<br />    <font color=\"navajowhite\">count</font>() <font color=\"navajowhite\">count</font><br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">GROUP BY</font> query<br /><font color=\"darkorange\">ORDER BY</font> duration <font color=\"darkorange\">desc</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"darkcyan\">$top</font>",
     "query": "select \nrow_number,\nrow_info.1 name,\nrow_info.2 total_rows,\nrow_info.3 total_bytes\nfrom\n(select groupArray((name,total_rows,total_bytes)) as row_info_list,arrayEnumerate(row_info_list) as index_list from (\n    SELECT\n        concat(database,'.',table) name,\n        sum(rows) total_rows,\n        sum(bytes_on_disk) total_bytes\n    FROM monitor.doge\n    GROUP BY name\n    ORDER BY total_rows desc ) t\n) array join row_info_list as row_info,\nindex_list as row_number\nLIMIT $top",
     "rawQuery": "select  row_number, row_info.1 name, row_info.2 total_rows, row_info.3 total_bytes from (select groupArray((name,total_rows,total_bytes)) as row_info_list,arrayEnumerate(row_info_list) as index_list from (     SELECT         concat(database,'.',table) name,         sum(rows) total_rows,         sum(bytes_on_disk) total_bytes     FROM monitor.doge     GROUP BY name     ORDER BY total_rows desc ) t ) array join row_info_list as row_info, index_list as row_number LIMIT 5",
     "round": "0s",
     "table": "query_log"
    }
   ]
  },
  {
   "title": "Request charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reqs/s by type: $type; user: $user; query type: $query_type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "database": "system",
       "dateColDataType": "event_date",
       "dateTimeColDataType": "event_time",
       "formattedQuery": "<font color=\"darkcyan\">$rate</font>(<font color=\"navajowhite\">count</font>() c)<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">where</font>  <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))",
       "query": "$rate(count() c)\nFROM $table\nwhere  type in ($type)\n    and initial_user in ($user)\n    and('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))",
       "rawQuery": "SELECT t, c/runningDifference(t/1000) cRate FROM ( SELECT (intDiv(toUInt32(event_time), 10) * 10) * 1000 AS t, count() c FROM system.query_log WHERE event_date >= toDate(1577952012) AND event_time >= toDateTime(1577952012) AND  type in (1,2,3,4)     and initial_user in ('default','','qqmusic_search_user','qqmusic_log_only_user','qqmusic_live_user')     and('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1)) GROUP BY t ORDER BY t)",
       "table": "query_log"
      }
     ]
    },
    {
     "title": "Query duration by type: $type; user: $user",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "database": "system",
       "dateColDataType": "event_date",
       "dateTimeColDataType": "event_time",
       "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms)  select_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br />    <font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'select'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
       "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms)  select_duration\nFROM $table\nWHERE\n    $timeFilter\n    AND type = 2\n    and positionCaseInsensitive(query,  'select') = 1\n    and initial_user in ($user)\nGROUP BY t\nORDER BY t",
       "rawQuery": "SELECT     (intDiv(toUInt32(event_time), 10) * 10) * 1000 as t,     avg(query_duration_ms)  select_duration FROM system.query_log WHERE     event_date >= toDate(1577952012) AND event_time >= toDateTime(1577952012)     AND type = 2     and positionCaseInsensitive(query,  'select') = 1     and initial_user in ('default','','qqmusic_search_user','qqmusic_log_only_user','qqmusic_live_user') GROUP BY t ORDER BY t",
       "table": "query_log"
      },
      {
       "database": "system",
       "dateColDataType": "event_date",
       "dateTimeColDataType": "event_time",
       "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t,<br />    <font color=\"navajowhite\">avg</font>(query_duration_ms) insert_duration<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font><br />    <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">2</font><br /><font color=\"yellow\">and</font> positionCaseInsensitive(query,  <font color=\"lightgreen\">'insert into'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font><br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br /><font color=\"darkorange\">GROUP BY</font> t<br /><font color=\"darkorange\">ORDER BY</font> t",
       "query": "SELECT\n    $timeSeries as t,\n    avg(query_duration_ms) insert_duration\nFROM $table\nWHERE\n    $timeFilter\n    AND type = 2\nand positionCaseInsensitive(query,  'insert into') = 1\n    and initial_user in ($user)\nGROUP BY t\nORDER BY t",
       "rawQuery": "SELECT     (intDiv(toUInt32(event_time), 10) * 10) * 1000 as t,     avg(query_duration_ms) insert_duration FROM system.query_log WHERE     event_date >= toDate(1577952012) AND event_time >= toDateTime(1577952012)     AND type = 2 and positionCaseInsensitive(query,  'insert into') = 1     and initial_user in ('default','','qqmusic_search_user','qqmusic_log_only_user','qqmusic_live_user') GROUP BY t ORDER BY t",
       "table": "query_log"
      }
     ]
    }
   ]
  },
  {
   "title": "Query log table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query log by type: $type; user: $user; query type: $query_type",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "database": "system",
       "dateColDataType": "event_date",
       "dateTimeColDataType": "event_time",
       "formattedQuery": "<font color=\"darkorange\">SELECT</font><br />    event_time,<br />    user,<br />    query_duration_ms duration,<br />    memory_usage memory,<br />    if(exception<font color=\"yellow\">!=</font><font color=\"lightgreen\">''</font>, <font color=\"lightgreen\">'fail'</font>, <font color=\"lightgreen\">'success'</font>) result,<br />    <font color=\"navajowhite\">concat</font>(<font color=\"navajowhite\">substring</font>(query,<font color=\"cornflowerblue\">1</font>,<font color=\"cornflowerblue\">120</font>), <font color=\"lightgreen\">'...'</font>) query<br /><font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font><br /><font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font><br />    <font color=\"yellow\">AND</font> <font color=\"darkorange\">type</font> <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$type</font>)<br />    <font color=\"yellow\">and</font> initial_user <font color=\"darkorange\">in</font> (<font color=\"darkcyan\">$user</font>)<br />    <font color=\"yellow\">and</font>(<font color=\"lightgreen\">'$query_type'</font> <font color=\"yellow\">=</font> <font color=\"lightgreen\">'all'</font> <font color=\"yellow\">or</font>(positionCaseInsensitive(query,  <font color=\"lightgreen\">'$query_type'</font>) <font color=\"yellow\">=</font> <font color=\"cornflowerblue\">1</font>))<br /><font color=\"darkorange\">ORDER BY</font> event_time <font color=\"darkorange\">DESC</font><br /><font color=\"darkorange\">LIMIT</font> <font color=\"cornflowerblue\">1000</font>",
       "query": "SELECT\n    event_time,\n    user,\n    query_duration_ms duration,\n    memory_usage memory,\n    if(exception!='', 'fail', 'success') result,\n    concat(substring(query,1,120), '...') query\nFROM $table\nWHERE $timeFilter\n    AND type in ($type)\n    and initial_user in ($user)\n    and('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))\nORDER BY event_time DESC\nLIMIT 1000",
       "rawQuery": "SELECT     event_time,     user,     query_duration_ms duration,     memory_usage memory,     if(exception!='', 'fail', 'success') result,     concat(substring(query,1,120), '...') query FROM system.query_log WHERE event_date >= toDate(1498209895) AND event_time >= toDateTime(1498209895)     AND type in (1,2,3,4)     and initial_user in ('default')     and('all' = 'all' or(positionCaseInsensitive(query,  'all') = 1)) ORDER BY event_time DESC LIMIT 1000",
       "table": "query_log"
      }
     ]
    }
   ]
  }
 ]
}