{
 "title": "clickhouse-各server负载差异",
 "description": "Clickhouse metrics, Monitoring Agent metrics",
 "tags": [
  "clickhouse",
  "Altinity",
  "operator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "process read bytes (G)",
   "type": "grafana-piechart-panel",
   "description": "Show network errors and distributed server-server connections failures",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(system_processes_read_bytes)by(ip)/1000000000",
     "legendFormat": " {{ip}}"
    }
   ]
  },
  {
   "title": "process written_bytes (G)",
   "type": "grafana-piechart-panel",
   "description": "Show network errors and distributed server-server connections failures",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(system_processes_written_bytes)by(ip)/1000000000",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "merge bytes_written_uncompressed(G) ",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(system_merges_bytes_written_uncompressed/1000000000)by(ip)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "merge bytes_read_uncompressed(G) ",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(system_merges_bytes_read_uncompressed/1000000000)by(ip)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "parts bytes_on_disk (G)",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(system_parts_bytes_on_disk)by(ip)/1000000000",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "parts data_uncompressed_bytes(G) ",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 16 },
   "format": "short",
   "valueName": "current"
  },
  {
   "title": "total query num",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_events_value{event='Query'}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "total select num",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_events_value{event='SelectQuery'}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "total fileopen num",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_events_value{event='FileOpen'}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "database num",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    { "expr": "system_databases_num", "legendFormat": " {{ip}}" }
   ]
  },
  {
   "title": "tables num",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(system_tables_num)by(ip)", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "columns num",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(system_columns_num)by(ip)", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "event query increase num in 1 day",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(system_events_value{event='Query'}[1d])",
     "legendFormat": " {{ip}}"
    }
   ]
  },
  {
   "title": "event select increase num in 1 day",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(system_events_value{event='SelectQuery'}[1d])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "event fileopen increase num in 10minute",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(system_events_value{event='FileOpen'}[1d])",
     "legendFormat": " {{ip}}"
    }
   ]
  },
  {
   "title": "merge elapsed(s)",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(system_merges_elapsed)by(ip)",
     "legendFormat": " {{ip}}"
    }
   ]
  },
  {
   "title": "merge num_parts ",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(system_merges_num_parts)by(ip)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "merge total_size_bytes_compressed(G) ",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(system_merges_total_size_bytes_compressed/1000000000)by(ip)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "merge total_size_marks(million) ",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(system_merges_total_size_marks/1000000)by(ip)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "merge rows_written(million)",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(system_merges_rows_written/1000000)by(ip)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "merge rows_read(million) ",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(system_merges_rows_read/1000000)by(ip)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "process memory_usage (G)",
   "type": "grafana-piechart-panel",
   "description": "Show network errors and distributed server-server connections failures",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(system_processes_memory_usage)by(ip)/1000000000",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "process read_rows",
   "type": "grafana-piechart-panel",
   "description": "Show network errors and distributed server-server connections failures",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 64 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(system_processes_read_rows)by(ip)",
     "legendFormat": " {{ip}}"
    }
   ]
  },
  {
   "title": "process written_rows ",
   "type": "grafana-piechart-panel",
   "description": "Show network errors and distributed server-server connections failures",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 64 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(system_processes_written_rows)by(ip)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "metrics query number",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 71 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_metrics_value{metric=\"Query\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "metrics merge number",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 71 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_metrics_value{metric=\"Merge\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "replicas-metric fetched number",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_metrics_value{metric=\"ReplicatedFetch\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "replicas-metric send number",
   "type": "grafana-piechart-panel",
   "description": "Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 78 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "system_metrics_value{metric=\"ReplicatedSend\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  }
 ]
}