{
 "title": "juno/clickhouse/airflow/superset 容器负载监控",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(kube_pod_info, host_ip)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{host_ip=~\"$instance\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "juno,clickhouse,airflow,superset,-"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"(.*$pod.*)\", container_name!=\"POD\", container_name!=\"\",namespace=~\"($namespace)\",instance=~\"($instance):10250\"})",
     "legendFormat": "Current: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{pod_name=~\"(.*$pod.*)\",container_name!=\"POD\",container_name!=\"\",namespace=~\"($namespace)\",instance=~\"($instance):10250\"}[1m]))",
     "legendFormat": "current {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"(.*$pod.*)\",namespace=~\"($namespace)\",instance=~\"($instance):10250\"}[1m])))",
     "legendFormat": " receive: {{ pod_name }} "
    },
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_transmit_bytes_total{pod_name=~\"(.*$pod.*)\",namespace=~\"($namespace)\",instance=~\"($instance):10250\"}[1m])))",
     "legendFormat": "send: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "fs I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_fs_reads_bytes_total{pod_name=~\"(.*$pod.*)\",namespace=~\"($namespace)\",instance=~\"($instance):10250\"}[1m])))",
     "legendFormat": " read: {{ pod_name }} "
    },
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_fs_writes_bytes_total{pod_name=~\"(.*$pod.*)\",namespace=~\"($namespace)\",instance=~\"($instance):10250\"}[1m])))",
     "legendFormat": "write: {{ pod_name }}"
    }
   ]
  }
 ]
}