{
 "title": "核心数据日报异常监控",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "App MAU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(nowx_mau) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "总MAU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(mau) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "严格DAU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(p_dau) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "宽松DAU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(dau) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "新增DAU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(reg_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "回流唤醒DAU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(react_dau) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "安卓-DAU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(dau) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = 11\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "IOS-DAU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(dau) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = 1\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "小程序DAU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(dau) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = 71\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "歌房小程序DAU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(dau) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = 73\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "K歌小程序DAU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(dau) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = 700\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "H5拉起DAU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(h5_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "人均时长(min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum( act_times / 60 / act_times_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "人均活跃天数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(p_mau_active_days / p_mau) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "抢麦人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(rob_micro_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "点歌人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(write_record_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "发布人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(post_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "播放人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(play_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "评论人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(comment_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "送花人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(flower_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "关注人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(follow_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "站外分享人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(share_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "发起-发布人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(chorus_gen_post_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "参与-发布人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(chorus_part_post_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "发起-录制人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(chorus_gen_write_record_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "发起-录制人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(chorus_gen_write_record_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "歌房创建人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(ktv_create_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "歌房进入人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(ktv_enter_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "直播发起人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(live_create_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  },
  {
   "title": "观看直播人数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(ftime, '%Y%m%d') as time_sec,\r\n  sum(live_enter_user) as value,\r\n  concat(platform, '') as metric\r\nFROM rd_qmkg_pushmail_index_log\r\nWHERE ftime >= date_format(date($__timeFrom()), '%Y%m%d') \r\nand ftime<=date_format(date($__timeTo()), '%Y%m%d')\r\nand platform = -914\r\ngroup by ftime, platform\r\nORDER BY ftime ASC"
    }
   ]
  }
 ]
}