{
 "title": "集群各机器负载差异总览",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cpu 使用率 %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\"}\n- node_memory_MemFree{job=\"node-exporter\"}\n- node_memory_Buffers{job=\"node-exporter\"}\n- node_memory_Cached{job=\"node-exporter\"}\n) * 100\n  /\nnode_memory_MemTotal{job=\"node-exporter\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "读io",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{job=\"node-exporter\"}[2m]))/1000000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "写io (GB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{job=\"node-exporter\"}[2m]))/1000000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "网络接收(GB)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes{job=\"node-exporter\", device!~\"lo\"}[5m]))/1000000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "网络发送",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes{job=\"node-exporter\",device!~\"lo\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}