{
 "title": "arctern-mysq流量",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": "aicloud,api,ifaas-building,test,yinli"
   }
  ]
 },
 "panels": [
  {
   "title": "arctern总流量/10m（总流量）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(create_time,10m),\n  \"all\" AS metric,\n  sum(num)\nFROM arctern\nWHERE\n  $__unixEpochFilter(create_time)\nGROUP BY 1,2\nORDER BY $__unixEpochGroup(create_time,10m)"
    }
   ]
  },
  {
   "title": "arctern各项目流量/10m（各项目）",
   "type": "graph",
   "description": "各个项目的访问流量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(create_time,10m),\n  project AS metric,\n  sum(num) AS \"num\"\nFROM arctern\nWHERE\n  $__unixEpochFilter(create_time)\nGROUP BY 1,2\nORDER BY $__unixEpochGroup(create_time,10m)"
    }
   ]
  },
  {
   "title": "arctern各距路径流量/10m（各路径）",
   "type": "graph",
   "description": "各路径的访问流量",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(create_time,10m),\n  path AS metric,\n  sum(num) AS \"num\"\nFROM arctern\nWHERE\n  $__unixEpochFilter(create_time)\nGROUP BY 1,2\nORDER BY $__unixEpochGroup(create_time,10m)"
    }
   ]
  },
  {
   "title": "arctern各项目各路径流量/10m（各项目各路径）",
   "type": "graph",
   "description": "各项目各路径的访问流量",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(create_time,10m),\n  path AS metric,\n  sum(num) AS \"num\"\nFROM arctern\nWHERE\n  $__unixEpochFilter(create_time) and project='${project}'\nGROUP BY 1,2\nORDER BY $__unixEpochGroup(create_time,10m)"
    }
   ]
  }
 ]
}