{
 "title": "客流分析",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job_name",
    "query": "traffic,traffic1,traffic_metrics"
   }
  ]
 },
 "panels": [
  { "title": "当前时间", "type": "grafana-clock-panel", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "总客流",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum($job_name/5)" }
   ]
  },
  {
   "title": "VIP客流",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.container_name:\"backend-mqtt-container\" AND log:mqtt",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "男女客流",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum($job_name/5)by(gender)" }
   ]
  },
  {
   "title": "男女比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum($job_name)by(gender)" }
   ]
  },
  {
   "title": "年龄分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum($job_name/5)by(age)" }
   ]
  },
  {
   "title": "屏幕客流",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum($job_name/5)by(deviceid)" }
   ]
  }
 ]
}