{
 "title": "kong",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": "label_values(service)" },
   { "name": "consumer", "label": "consumer", "query": "label_values(consumer)" },
   { "name": "route", "label": "route", "query": "label_values(route)" },
   { "name": "code", "label": "code", "query": "label_values(code)" }
  ]
 },
 "panels": [
  {
   "title": "流量(/m)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_request_total{service=~\"($service)\",consumer=~\"($consumer)\",route=~\"($route)\",code=~\"($code)\"}[1m]))"
    }
   ]
  },
  {
   "title": "男女客流(/s)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(grpc_metric{project=~\"($project)\",age=~\"($age)\",device_id=~\"($device_id)\"}[1m]))by(gender)"
    }
   ]
  },
  {
   "title": "摄像头客流",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(grpc_metric{project=~\"($project)\",age=~\"($age)\",gender=~\"($gender)\"}[1m]))by(device_id)"
    }
   ]
  },
  {
   "title": "男女比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 36 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(grpc_metric{project=~\"($project)\",age=~\"($age)\",device_id=~\"($device_id)\"}[1h]))by(gender)"
    }
   ]
  },
  {
   "title": "摄像头客流",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 36 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(grpc_metric{project=~\"($project)\",age=~\"($age)\",gender=~\"($gender)\"}[1h]))by(device_id)"
    }
   ]
  },
  {
   "title": "年龄分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(grpc_metric{project=~\"($project)\",gender=~\"($gender)\",device_id=~\"($device_id)\"}[1h]))by(age)"
    }
   ]
  }
 ]
}