{
 "title": "Nodes-报警",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(node_boot_time{job=\"node-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage-192.168.0.51",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}\n- node_memory_Cached{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}\n) * 100\n  /\nnode_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}\n"
    }
   ]
  },
  {
   "title": "Memory Usage-192.168.0.52",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}\n- node_memory_Cached{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}\n) * 100\n  /\nnode_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}\n"
    }
   ]
  },
  {
   "title": "Memory Usage-192.168.0.53",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}\n- node_memory_Cached{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}\n) * 100\n  /\nnode_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}\n"
    }
   ]
  },
  {
   "title": "Memory Usage-192.168.0.55",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}\n- node_memory_Cached{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}\n) * 100\n  /\nnode_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}\n"
    }
   ]
  },
  {
   "title": "Memory Usage-192.168.0.56",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}\n- node_memory_Cached{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}\n) * 100\n  /\nnode_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}\n"
    }
   ]
  },
  {
   "title": "CPU-192.168.0.51",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"192.168.0.51:9100\"}[5m])) * 100)",
     "legendFormat": "192.168.0.51:9100"
    }
   ]
  },
  {
   "title": "CPU-192.168.0.52",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"192.168.0.52:9100\"}[5m])) * 100)",
     "legendFormat": "192.168.0.52:9100"
    }
   ]
  },
  {
   "title": "CPU-192.168.0.53",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"192.168.0.53:9100\"}[5m])) * 100)",
     "legendFormat": "192.168.0.53:9100"
    }
   ]
  },
  {
   "title": "CPU-192.168.0.55",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"192.168.0.55:9100\"}[5m])) * 100)",
     "legendFormat": "192.168.0.55:9100"
    }
   ]
  },
  {
   "title": "CPU-192.168.0.56",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"192.168.0.56:9100\"}[5m])) * 100)",
     "legendFormat": "192.168.0.56:9100"
    }
   ]
  },
  {
   "title": "内存利用率(报警使用)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}\n- node_memory_Cached{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}\n) \n  /\nnode_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}\n",
     "legendFormat": "192.168.0.51"
    },
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}\n- node_memory_Cached{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}\n) \n  /\nnode_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}\n",
     "legendFormat": "192.168.0.52"
    },
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}\n- node_memory_Cached{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}\n) \n  /\nnode_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}\n",
     "legendFormat": "192.168.0.53"
    },
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}\n- node_memory_Cached{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}\n) \n  /\nnode_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}\n",
     "legendFormat": "192.168.0.55"
    },
    {
     "expr": "(\n  node_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}\n- node_memory_MemFree{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}\n- node_memory_Buffers{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}\n- node_memory_Cached{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}\n) \n  /\nnode_memory_MemTotal{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}\n",
     "legendFormat": "192.168.0.56"
    }
   ]
  },
  {
   "title": "CPU利用率(报警使用)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"192.168.0.51:9100\"}[5m])) * 100)",
     "legendFormat": "192.168.0.51"
    },
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"192.168.0.52:9100\"}[5m])) * 100)",
     "legendFormat": "192.168.0.52"
    },
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"192.168.0.53:9100\"}[5m])) * 100)",
     "legendFormat": "192.168.0.53"
    },
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"192.168.0.55:9100\"}[5m])) * 100)",
     "legendFormat": "192.168.0.55"
    },
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu{mode=\"idle\", instance=~\"192.168.0.56:9100\"}[5m])) * 100)",
     "legendFormat": "192.168.0.56"
    }
   ]
  },
  {
   "title": "磁盘利用率(报警使用)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.51:9100\"})\n- sum(node_filesystem_avail{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.51:9100\"})\n)\n  /\nsum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.51:9100\"})\n",
     "legendFormat": "192.168.0.51"
    },
    {
     "expr": "(\n  sum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.52:9100\"})\n- sum(node_filesystem_avail{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.52:9100\"})\n)\n  /\nsum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.52:9100\"})\n",
     "legendFormat": "192.168.0.52"
    },
    {
     "expr": "(\n  sum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.53:9100\"})\n- sum(node_filesystem_avail{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.53:9100\"})\n)\n  /\nsum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.53:9100\"})\n",
     "legendFormat": "192.168.0.53"
    },
    {
     "expr": "(\n  sum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.55:9100\"})\n- sum(node_filesystem_avail{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.55:9100\"})\n)\n  /\nsum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.55:9100\"})\n",
     "legendFormat": "192.168.0.55"
    },
    {
     "expr": "(\n  sum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.56:9100\"})\n- sum(node_filesystem_avail{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.56:9100\"})\n)\n  /\nsum(node_filesystem_size{job=\"node-exporter\", device!=\"rootfs\", instance=\"192.168.0.56:9100\"})\n",
     "legendFormat": "192.168.0.56"
    }
   ]
  },
  {
   "title": "系统负载(报警使用)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}",
     "legendFormat": "192.168.0.51"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}",
     "legendFormat": "192.168.0.52"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}",
     "legendFormat": "192.168.0.53"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}",
     "legendFormat": "192.168.0.55"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}",
     "legendFormat": "192.168.0.56"
    }
   ]
  },
  {
   "title": "io写入速率(报警使用)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}[2m]))",
     "legendFormat": "192.168.0.51"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}[2m]))",
     "legendFormat": "192.168.0.52"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}[2m]))",
     "legendFormat": "192.168.0.53"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}[2m]))",
     "legendFormat": "192.168.0.55"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}[2m]))",
     "legendFormat": "192.168.0.56"
    }
   ]
  },
  {
   "title": "io读速率(报警使用)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{job=\"node-exporter\", instance=\"192.168.0.51:9100\"}[2m]))",
     "legendFormat": "192.168.0.51"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{job=\"node-exporter\", instance=\"192.168.0.52:9100\"}[2m]))",
     "legendFormat": "192.168.0.52"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{job=\"node-exporter\", instance=\"192.168.0.53:9100\"}[2m]))",
     "legendFormat": "192.168.0.53"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{job=\"node-exporter\", instance=\"192.168.0.55:9100\"}[2m]))",
     "legendFormat": "192.168.0.55"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{job=\"node-exporter\", instance=\"192.168.0.56:9100\"}[2m]))",
     "legendFormat": "192.168.0.56"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{job=\"node-exporter\", instance=\"$instance\", device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{job=\"node-exporter\", instance=\"$instance\", device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}