{
 "title": "Zookeeper Overview",
 "description": "Zookeeper Overview",
 "tags": [
  "zookeeper",
  "metrics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(zk_up,instance)" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(zk_num_alive_connections{instance=~\"$instance\"})",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "正在处理请求数",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zk_outstanding_requests{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zk_open_file_descriptor_count{instance=~\"$instance\"})/sum(zk_max_file_descriptor_count{instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(zk_max_latency{instance=~\"$instance\"})",
     "legendFormat": "max_latency"
    },
    {
     "expr": "min(zk_min_latency{instance=~\"$instance\"})",
     "legendFormat": "min_latency"
    },
    {
     "expr": "avg(zk_avg_latency{instance=~\"$instance\"})",
     "legendFormat": "avg_latency"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zk_packets_sent{instance=~\"$instance\"})",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(zk_packets_received{instance=~\"$instance\"})",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Approximate data size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(zk_approximate_data_size{instance=~\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zookeeper",
     "select": [
      [
       { "params": [ "approximate_data_size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "File descriptor count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Max",
     "expr": "zk_open_file_descriptor_count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "open_file_count",
     "measurement": "zookeeper",
     "select": [
      [
       { "params": [ "max_file_descriptor_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Open",
     "expr": "zk_max_file_descriptor_count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max_file_count",
     "measurement": "zookeeper",
     "select": [
      [
       { "params": [ "open_file_descriptor_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Watch Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Count",
     "expr": "sum(zk_watch_count{instance=~\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "watch_count",
     "measurement": "zookeeper",
     "select": [
      [
       { "params": [ "watch_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ZNode Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(zk_znode_count{instance=~\"$instance\"})",
     "legendFormat": "max_znode_count"
    }
   ]
  }
 ]
}